let num1 = 9.2546;
let num2 = Math.floor(num1);  //Arredonda para baixo
let num3 = Math.ceil(num1);  //Arredonda para cima
let num4 = Math.round(num1);//Arredonda para o mais próximo
console.log(num2);
console.log(num3);
console.log(num1)

console.log(Math.max(1,2,3,4,5,6)); // traz o maior da sequência
console.log(Math.random()); // gera números aleatórios 
console.log(Math.PI);
console.log(Math.pow(2, 10));


