let num1 = 1500;   //number
let num2 = 2.5;//number
let num3 = 10.3216512;
console.log(num1 + num2);//number
// num1 = num1.toString();
console.log(num1.toString() + num2);//String

//repesentação binária
console.log(num1.toString(2));

//"Round"               |qtd de decimais|
console.log(num3.toFixed(2));

// O número é inteiro? (TRUE and FALSE)
console.log(Number.isInteger(num3));

// É um NaN? (TRUE and FALSE)
console.log(Number.isNaN(num2));