// Criando Variáveis com LET

let nome = 'Neymar'; //String, Declarando e inicializando
let nome2; // Apenas Declarando
nome2 = 'Ronaldo' //Inicializando

// Não podemos criar variáveis com palavras reservadas da linguagem
// Variáveis precisam ter nomes significativos
// Não podemos começar o nome de uma variável com um número
// O nome de uma variável não deve conter espaços ou traços
// Utilizamos camelCase = nomeCliente
// Case-sentitive
// Não podemos redeclarar variáveis com Let
// Não utilize VAR, utilize LET


console.log(nome2);
console.log(nome,'nasceu em 1984.');
console.log('Em 2000', nome, 'conheceu Maria.');
console.log('Maria teve 1 filho com', nome,'em 2015.');
console.log('O filho de', nome,'se chama Eduardo');
